# Generated by Django 2.2.7 on 2020-06-24 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Help => Name of the product', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Help => Description of the product', max_length=250, unique=True)),
                ('nutritional_values', models.IntegerField(help_text='Help => Description of the Nutritional values')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='NutritionalValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Help => Description od the nutritional value', max_length=50)),
                ('unit', models.CharField(help_text='Help => Description od the unit (kcal, gr.)', max_length=5)),
                ('nutritionalvalues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nutritional Values',
                'unique_together': {('nutritionalvalues', 'name')},
            },
        ),
    ]
