# Generated by Django 2.2.7 on 2020-09-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='unit',
            field=models.DecimalField(decimal_places=2, help_text='Help => (1.000)', max_digits=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutritional_values',
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_values',
            field=models.ManyToManyField(to='products.NutritionalValues'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[('0', 'Inactive'), ('1', 'Active')], default=True),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionalvalues',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nutritionalvalues',
            name='nutritionalvalues',
        ),
    ]
